import type { ProviderCatalogPlugin } from "@nextclaw/core";
import { dashscopeCodingPlanProviderSpec } from "./dashscope-coding-plan.js";
export const builtinProviderPlugin: ProviderCatalogPlugin = { id: "builtin-runtime-providers",
  providers: [
    {
      name: "nextclaw",
      keywords: ["nextclaw", "dashscope/", "qwen3.5", "qwen"],
      envKey: "NEXTCLAW_API_KEY",
      displayName: "NextClaw Built-in",
      modelPrefix: "nextclaw",
      litellmPrefix: "nextclaw",
      skipPrefixes: [],
      envExtras: [],
      isGateway: true,
      isLocal: false,
      detectByKeyPrefix: "nc_free_",
      detectByBaseKeyword: "nextclaw.io",
      defaultApiBase: "https://ai-gateway-api.nextclaw.io/v1",
      defaultModels: [
        "dashscope/qwen3.5-plus",
        "dashscope/qwen3.5-flash",
        "dashscope/qwen3.5-122b-a10b",
        "dashscope/qwen3.5-35b-a3b"
      ],
      stripModelPrefix: false,
      modelOverrides: []
    },
    {
      name: "openrouter",
      keywords: ["openrouter"],
      envKey: "OPENROUTER_API_KEY",
      displayName: "OpenRouter",
      modelPrefix: "openrouter",
      litellmPrefix: "openrouter",
      skipPrefixes: [],
      envExtras: [],
      isGateway: true,
      isLocal: false,
      detectByKeyPrefix: "sk-or-",
      detectByBaseKeyword: "openrouter",
      defaultApiBase: "https://openrouter.ai/api/v1",
      defaultModels: [
        "openrouter/minimax/minimax-m2.5",
        "openrouter/google/gemini-3-flash-preview",
        "openrouter/deepseek/deepseek-v3.2",
        "openrouter/x-ai/grok-4.1-fast",
        "openrouter/z-ai/glm-5",
        "openrouter/anthropic/claude-opus-4.6",
        "openrouter/openai/gpt-5.3-codex"
      ],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "openrouter.svg"
    },
    {
      name: "aihubmix",
      keywords: ["aihubmix"],
      envKey: "OPENAI_API_KEY",
      displayName: "AiHubMix",
      modelPrefix: "aihubmix",
      litellmPrefix: "openai",
      skipPrefixes: [],
      envExtras: [],
      isGateway: true,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "aihubmix",
      defaultApiBase: "https://aihubmix.com/v1",
      defaultModels: ["aihubmix/gpt-5.3-codex", "aihubmix/claude-opus-4.6", "aihubmix/gemini-3.1-pro-preview"],
      visionModels: ["aihubmix/gemini-3.1-pro-preview", "aihubmix/gpt-5.4"],
      stripModelPrefix: true,
      modelOverrides: [],
      logo: "aihubmix.png"
    },
    {
      name: "anthropic",
      keywords: ["anthropic", "claude"],
      envKey: "ANTHROPIC_API_KEY",
      displayName: "Anthropic",
      modelPrefix: "anthropic",
      litellmPrefix: "anthropic",
      skipPrefixes: ["anthropic/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.anthropic.com",
      defaultModels: ["anthropic/claude-opus-4-6", "anthropic/claude-sonnet-4-6"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "anthropic.svg"
    },
    {
      name: "openai",
      keywords: ["openai", "gpt"],
      envKey: "OPENAI_API_KEY",
      displayName: "OpenAI",
      modelPrefix: "openai",
      litellmPrefix: "openai",
      skipPrefixes: ["openai/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.openai.com/v1",
      defaultModels: ["openai/gpt-5.3-codex", "openai/gpt-5-mini", "openai/gpt-5-nano"],
      visionModels: ["openai/gpt-5.4"],
      stripModelPrefix: false,
      modelOverrides: [],
      supportsWireApi: true,
      wireApiOptions: ["auto", "chat", "responses"],
      defaultWireApi: "auto",
      logo: "openai.svg"
    },
    {
      name: "deepseek",
      keywords: ["deepseek"],
      envKey: "DEEPSEEK_API_KEY",
      displayName: "DeepSeek",
      modelPrefix: "deepseek",
      litellmPrefix: "deepseek",
      skipPrefixes: ["deepseek/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.deepseek.com",
      defaultModels: ["deepseek/deepseek-chat", "deepseek/deepseek-reasoner"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "deepseek.png"
    },
    {
      name: "gemini",
      keywords: ["gemini"],
      envKey: "GEMINI_API_KEY",
      displayName: "Gemini",
      modelPrefix: "gemini",
      litellmPrefix: "gemini",
      skipPrefixes: ["gemini/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://generativelanguage.googleapis.com/v1beta/openai",
      defaultModels: ["gemini/gemini-3.1-pro-preview", "gemini/gemini-3-flash-preview"],
      visionModels: ["gemini/gemini-3.1-pro-preview", "gemini/gemini-3-flash-preview"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "gemini.svg"
    },
    {
      name: "zhipu",
      keywords: ["zhipu", "glm", "zai"],
      envKey: "ZAI_API_KEY",
      displayName: "Zhipu AI",
      modelPrefix: "zai",
      litellmPrefix: "zai",
      skipPrefixes: ["zhipu/", "zai/", "openrouter/", "hosted_vllm/"],
      envExtras: [["ZHIPUAI_API_KEY", "{api_key}"]],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://open.bigmodel.cn/api/paas/v4",
      defaultModels: ["zai/glm-5"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "zhipu.svg"
    },
    {
      name: "dashscope",
      keywords: ["qwen", "dashscope"],
      envKey: "DASHSCOPE_API_KEY",
      displayName: "DashScope",
      modelPrefix: "dashscope",
      litellmPrefix: "dashscope",
      skipPrefixes: ["dashscope/", "openrouter/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://dashscope.aliyuncs.com/compatible-mode/v1",
      defaultModels: [
        "dashscope/qwen3.5-plus",
        "dashscope/qwen3.5-flash",
        "dashscope/qwen3.5-397b-a17b",
        "dashscope/qwen3.5-122b-a10b",
        "dashscope/qwen3.5-35b-a3b",
        "dashscope/qwen3.5-27b"
      ],
      stripModelPrefix: false,
      modelOverrides: [],
      supportsResponsesApi: false,
      logo: "dashscope.png"
    },
    dashscopeCodingPlanProviderSpec,
    {
      name: "qwen-portal",
      keywords: ["qwen-portal", "qwen"],
      envKey: "QWEN_PORTAL_TOKEN",
      displayName: "Qwen Portal",
      modelPrefix: "qwen-portal",
      litellmPrefix: "qwen-portal",
      skipPrefixes: ["qwen-portal/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "portal.qwen.ai",
      defaultApiBase: "https://portal.qwen.ai/v1",
      defaultModels: ["qwen-portal/coder-model", "qwen-portal/vision-model"],
      visionModels: ["qwen-portal/vision-model"],
      stripModelPrefix: false,
      modelOverrides: [],
      auth: {
        kind: "device_code",
        displayName: "Qwen OAuth",
        baseUrl: "https://chat.qwen.ai",
        deviceCodePath: "/api/v1/oauth2/device/code",
        tokenPath: "/api/v1/oauth2/token",
        clientId: "f0304373b74a44d2b584a3fb70ca9e56",
        scope: "openid profile email model.completion",
        grantType: "urn:ietf:params:oauth:grant-type:device_code",
        usePkce: true,
        cliCredential: {
          path: "~/.qwen/oauth_creds.json",
          accessTokenField: "access_token",
          refreshTokenField: "refresh_token",
          expiresAtField: "expiry_date"
        },
        note: {
          zh: "通过浏览器登录 Qwen 后即可在 NextClaw 中使用该 Provider。",
          en: "Log in to Qwen in your browser, then use this provider in NextClaw."
        }
      }
    },
    {
      name: "moonshot",
      keywords: ["moonshot", "kimi"],
      envKey: "MOONSHOT_API_KEY",
      displayName: "Moonshot",
      modelPrefix: "moonshot",
      litellmPrefix: "moonshot",
      skipPrefixes: ["moonshot/", "openrouter/"],
      envExtras: [["MOONSHOT_API_BASE", "{api_base}"]],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.moonshot.ai/v1",
      defaultModels: ["moonshot/kimi-k2.5"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "moonshot.png"
    },
    {
      name: "minimax",
      keywords: ["minimax"],
      envKey: "MINIMAX_API_KEY",
      displayName: "MiniMax",
      modelPrefix: "minimax",
      litellmPrefix: "minimax",
      skipPrefixes: ["minimax/", "openrouter/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.minimaxi.com/v1",
      defaultModels: ["minimax/MiniMax-M2.7", "minimax/MiniMax-M2.7-highspeed", "minimax/MiniMax-M2.5", "minimax/MiniMax-M2.5-highspeed"],
      stripModelPrefix: false,
      modelOverrides: [],
      supportsWireApi: true,
      wireApiOptions: ["auto", "chat", "responses"],
      defaultWireApi: "chat",
      logo: "minimax.svg",
      apiBaseHelp: {
        zh: "MiniMax 中国区请使用 https://api.minimaxi.com/v1；海外请使用 https://api.minimax.io/v1。AI Coding Tools 推荐使用 MiniMax-M2.7，并将 Wire API 设为 Chat。",
        en: "Use https://api.minimaxi.com/v1 for Mainland China accounts, and https://api.minimax.io/v1 for overseas accounts. For AI Coding Tools, prefer MiniMax-M2.7 with Wire API set to Chat."
      }
    },
    {
      name: "minimax-portal",
      keywords: ["minimax-portal", "minimax"],
      envKey: "MINIMAX_PORTAL_TOKEN",
      displayName: "MiniMax Portal",
      modelPrefix: "minimax-portal",
      litellmPrefix: "minimax-portal",
      skipPrefixes: ["minimax-portal/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.minimax.io/v1",
      defaultModels: ["minimax-portal/MiniMax-M2.5", "minimax-portal/MiniMax-M2.5-highspeed"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "minimax.svg",
      apiBaseHelp: {
        zh: "OAuth Global 默认使用 https://api.minimax.io/v1；OAuth 中国区默认使用 https://api.minimaxi.com/v1。",
        en: "OAuth Global uses https://api.minimax.io/v1 by default; OAuth CN uses https://api.minimaxi.com/v1."
      },
      auth: {
        kind: "device_code",
        protocol: "minimax_user_code",
        displayName: "MiniMax OAuth",
        baseUrl: "https://api.minimax.io",
        deviceCodePath: "/oauth/code",
        tokenPath: "/oauth/token",
        clientId: "78257093-7e40-4613-99e0-527b14b39113",
        scope: "group_id profile model.completion",
        grantType: "urn:ietf:params:oauth:grant-type:user_code",
        usePkce: true,
        defaultMethodId: "cn",
        methods: [
          {
            id: "global",
            label: {
              zh: "Global（海外）",
              en: "Global"
            },
            hint: {
              zh: "适用于海外用户，默认 API Base 为 https://api.minimax.io/v1。",
              en: "For international users. Default API base: https://api.minimax.io/v1."
            },
            baseUrl: "https://api.minimax.io",
            defaultApiBase: "https://api.minimax.io/v1"
          },
          {
            id: "cn",
            label: {
              zh: "中国区（CN）",
              en: "China Mainland (CN)"
            },
            hint: {
              zh: "适用于中国区用户，默认 API Base 为 https://api.minimaxi.com/v1。",
              en: "For Mainland China users. Default API base: https://api.minimaxi.com/v1."
            },
            baseUrl: "https://api.minimaxi.com",
            defaultApiBase: "https://api.minimaxi.com/v1"
          }
        ],
        note: {
          zh: "通过浏览器完成 MiniMax OAuth 授权后即可使用，无需手动填写 API Key。",
          en: "Complete MiniMax OAuth in browser to use this provider without manually entering an API key."
        }
      }
    },
    {
      name: "vllm",
      keywords: ["vllm"],
      envKey: "HOSTED_VLLM_API_KEY",
      displayName: "vLLM/Local",
      modelPrefix: "hosted_vllm",
      litellmPrefix: "hosted_vllm",
      skipPrefixes: [],
      envExtras: [],
      isGateway: false,
      isLocal: true,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "http://127.0.0.1:8000/v1",
      defaultModels: [
        "hosted_vllm/meta-llama/Llama-3.1-8B-Instruct",
        "hosted_vllm/Qwen/Qwen2.5-7B-Instruct"
      ],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "vllm.svg"
    },
    {
      name: "groq",
      keywords: ["groq"],
      envKey: "GROQ_API_KEY",
      displayName: "Groq",
      modelPrefix: "groq",
      litellmPrefix: "groq",
      skipPrefixes: ["groq/"],
      envExtras: [],
      isGateway: false,
      isLocal: false,
      detectByKeyPrefix: "",
      detectByBaseKeyword: "",
      defaultApiBase: "https://api.groq.com/openai/v1",
      defaultModels: ["groq/openai/gpt-oss-120b", "groq/llama-3.1-8b-instant"],
      stripModelPrefix: false,
      modelOverrides: [],
      logo: "groq.svg"
    }
  ]
};
